on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ateliermecanique-ws
      - name: Run Gradle build
        run: ./gradlew build
        working-directory: ateliermecanique-ws
#      - name: Run Selenium tests
#        run: ./gradlew build # This might be redundant if your build already runs the tests
#        working-directory: ateliermecanique-ws




